dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
install: npm install
script:
  # - npm run test
  - npm run build-deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: "dist"
  on:
    branch: "master"